-- =============================================================
-- 06 · Reports — the heart of the Resident Portal
-- A report is a resident-submitted issue. It only becomes an
-- INCIDENT after AI analysis + barangay review/verification.
-- =============================================================

CREATE TABLE reports (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_number VARCHAR(30) NOT NULL UNIQUE,          -- RPT-2026-000001 (generated by trigger)
    resident_id   UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    category_id   UUID REFERENCES categories(id) ON DELETE SET NULL,
    title         VARCHAR(200) NOT NULL,
    description   TEXT NOT NULL,
    status_id     UUID NOT NULL REFERENCES incident_statuses(id) ON DELETE RESTRICT,
    priority_id   UUID REFERENCES priorities(id) ON DELETE SET NULL,
    source        report_source NOT NULL DEFAULT 'WEB_PORTAL',
    submitted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    verified_at   TIMESTAMPTZ,
    closed_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One report → one primary GIS location
CREATE TABLE report_locations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id       UUID NOT NULL UNIQUE REFERENCES reports(id) ON DELETE CASCADE,
    latitude        DOUBLE PRECISION NOT NULL,
    longitude       DOUBLE PRECISION NOT NULL,
    location        GEOMETRY(Point, 4326) NOT NULL,     -- kept in sync by trigger
    address         TEXT,
    barangay_id     UUID REFERENCES barangays(id) ON DELETE SET NULL,
    zone_id         UUID REFERENCES zones(id) ON DELETE SET NULL,
    accuracy        DOUBLE PRECISION,                   -- meters, from device GPS
    location_source VARCHAR(30),                        -- GPS | MAP_PIN | ADDRESS_GEOCODE
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT report_lat_range CHECK (latitude  BETWEEN  -90 AND  90),
    CONSTRAINT report_lon_range CHECK (longitude BETWEEN -180 AND 180)
);

-- Photos / videos / documents attached by the resident
CREATE TABLE report_media (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id     UUID NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    uploaded_by   UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    file_url      TEXT NOT NULL,
    file_type     media_type NOT NULL,
    mime_type     VARCHAR(100),
    file_size     BIGINT,                               -- bytes
    storage_path  TEXT,                                 -- internal object-store path
    thumbnail_url TEXT,
    metadata      JSONB NOT NULL DEFAULT '{}',          -- width/height, duration, EXIF…
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reports_resident  ON reports(resident_id);
CREATE INDEX idx_reports_status    ON reports(status_id);
CREATE INDEX idx_reports_category  ON reports(category_id);
CREATE INDEX idx_reports_submitted ON reports(submitted_at DESC);
CREATE INDEX idx_report_media_report ON report_media(report_id);
