-- =============================================================
-- 09 · Incidents — a VERIFIED report becomes an official incident
-- REPORT → AI ANALYSIS → BARANGAY REVIEW → VERIFIED → INCIDENT
-- =============================================================

CREATE TABLE incidents (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_number  VARCHAR(30) NOT NULL UNIQUE,        -- INC-2026-000001 (generated by trigger)
    report_id        UUID NOT NULL UNIQUE REFERENCES reports(id) ON DELETE CASCADE,
    category_id      UUID REFERENCES categories(id) ON DELETE SET NULL,
    status_id        UUID NOT NULL REFERENCES incident_statuses(id) ON DELETE RESTRICT,
    priority_id      UUID REFERENCES priorities(id) ON DELETE SET NULL,
    barangay_id      UUID NOT NULL REFERENCES barangays(id) ON DELETE RESTRICT,
    location_id      UUID NOT NULL UNIQUE REFERENCES report_locations(id) ON DELETE RESTRICT,
    verified_by      UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    verified_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    assigned_at      TIMESTAMPTZ,
    resolved_at      TIMESTAMPTZ,
    closed_at        TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_incidents_barangay ON incidents(barangay_id);
CREATE INDEX idx_incidents_status   ON incidents(status_id);
CREATE INDEX idx_incidents_priority ON incidents(priority_id);
CREATE INDEX idx_incidents_category ON incidents(category_id);
